name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or replace 'main' with the branch you use for your code

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use the Node.js version you are using

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Gatsby site
      - name: Build the site
        run: npm run build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Uses GitHub token for authentication
          publish_dir: ./public  # The directory Gatsby outputs the build to
